### ISSUE TITLE
The integration fails to setup if soundbar is offline

### ISSUE THREAD

**Issue by diegocjorge** [samuelspagl/ha_samsung_soundbar#21]
Hey there,

Just wanted to flag an issue with the integration. If the soundbar is offline when Home Assistant is restarted the integration fails to set up. It’s a bit of a pain because we have to manually restart Home Assistant or the integration to get things back up and running.

It’d be cool if the integration could just mark the soundbar as ‘unavailable’ and keep going, checking now and then to see if the soundbar’s back online.

I’ve attached the error message from the log below. Hope this helps!

Cheers!

```
2024-03-05 05:56:46.507 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry samsung_soundbar for samsung_soundbar
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/samsung_soundbar/__init__.py", line 50, in async_setup_entry
await soundbar_device.update()
File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 49, in update
await self._update_soundmode()
File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 69, in _update_soundmode
await self.update_execution_data(["/sec/networkaudio/soundmode"])
File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 363, in update_execution_data
return await self.device.command("main", "execute", "execute", argument)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pysmartthings/device.py", line 842, in command
response = await self._api.post_device_command(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pysmartthings/api.py", line 147, in post_device_command
return await self.post(API_DEVICE_COMMAND.format(device_id=device_id), data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pysmartthings/api.py", line 395, in post
return await self.request("post", self._api_base + resource, data=data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pysmartthings/api.py", line 376, in request
resp.raise_for_status()
File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 409, message='Conflict', url=URL('https://api.smartthings.com/v1/devices/0f97098c-9bc0-9006-8519-30d00620b51f/commands')
```

**Comment by samuelspagl** [comment]
Hi @diegocjorge,

Im currently on vacation but will take a look at it as soon as I am back and have some free time. 

The issue definitely makes sense, and I think that I also saw that in my end. 

There are a few things that I wanna check, especially whether the 409 while fetching the "extra" capabilities is due to the soundbar being offline :)

**Comment by samuelspagl** [comment]
Hi @diegocjorge 

I suspect your issue to be similar to #13, as having the soundbar disconnected from wifi / completly powered off (plugged out) will probably look the same for the SmartThings Api.

I added the `ConfigEntryNotReady` exception in the setup process to let HomeAssistant start a retry process. I still have to test it out tho.

**Comment by diegocjorge** [comment]
Cool, thanks!
