### ISSUE TITLE
Integration not working? TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by DR-PLANTECHSTEIN** [samuelspagl/ha_samsung_soundbar#36]
Can't seem to get the integration working. I've got a nabu casa trial, 900c soundbar, got the API and device ID. Any idea?

```
Error setting up entry samsung_soundbar for samsung_soundbar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/samsung_soundbar/__init__.py", line 52, in async_setup_entry
    await soundbar_device.update()
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 52, in update
    await self._update_soundmode()
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 74, in _update_soundmode
    payload = await self.get_execute_status()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 390, in get_execute_status
    return dict["data"]["value"]["payload"]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by DR-PLANTECHSTEIN** [comment]
BETA fixed it.

**Comment by samuelspagl** [comment]
The Released version (master) should now also work :)
