### ISSUE TITLE
Bug - using Bearer Token instead of device id

### ISSUE THREAD

**Issue by daniel-hursan** [samuelspagl/ha_samsung_soundbar#47]
Hey, you have a bug in the code.
When setting up the integration, with all options checked, you're using the Bearer Token instead of the Device Id
I checked the logs and my token is sent as the device id, which is incorrect

FYI - if I use Postman and sent a GET request using my device id, and the bearer token, it works correctly, I get device info

Thanks for your work, looking forward to see this fixed.
All the best,
Daniel

2024-11-24 22:03:55.934 ERROR (MainThread) [custom_components.samsung_soundbar.config_flow] The ConfigFlow triggered an exception 403, message='Forbidden', url='https://api.smartthings.com/v1/devices/THIS_SHOULD_BE_DEVICE_ID_NOT_BEARER_TOKEN'
2024-11-24 22:04:36.353 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry samsung_soundbar for samsung_soundbar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/samsung_soundbar/__init__.py", line 69, in async_setup_entry
    await soundbar_device.update()
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 66, in update
    await self._update_soundmode()
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 92, in _update_soundmode
    payload = await self.get_execute_status()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 459, in get_execute_status
    return dict_stuff["data"]["value"]["payload"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by lonevvolf** [comment]
I think am hitting this - seems to fail connection if _any_ items are selected in the configuration.

**Comment by samuelspagl** [comment]
Hi there ✌️ I'll try to take a look at it this weekend :)

**Comment by blueman007** [comment]
Same error.
