### ISSUE TITLE
Samsung will break this integration (for new users) on Dec 30

### ISSUE THREAD

**Issue by NewsGuyTor** [samuelspagl/ha_samsung_soundbar#50]
https://community.smartthings.com/t/changes-to-personal-access-tokens-pat/292019

TLDR: Newly generated PATs will only work for 24 hours, which will be absurdly annoying for new users of this extension, so a change to oauth is needed.

**Comment by samuelspagl** [comment]
@NewsGuyTor Thanks for telling me that. I didn't know about this.

Nice, another thing to change. For me this was working fine, also as one user stated in the forum, bringing this up right upon christmas is just not the nicest way 😞.

Generally I don't see a problem with implementing oAuth, the only question I have is where to register the daily refresh token handler ❓. 

I really don't know weather I will get to this before the end of the year, but I'll try my best.

**Comment by troyhodges** [comment]
:( was I one day late?...

Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 11:28:39 AM (2 occurrences)
Last logged: 11:33:21 AM

Error setting up entry samsung_soundbar for samsung_soundbar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/samsung_soundbar/__init__.py", line 69, in async_setup_entry
    await soundbar_device.update()
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 66, in update
    await self._update_soundmode()
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 92, in _update_soundmode
    payload = await self.get_execute_status()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/samsung_soundbar/api_extension/SoundbarDevice.py", line 459, in get_execute_status
    return dict_stuff["data"]["value"]["payload"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by wilcocsjr** [comment]
Are there any plans to update this integration to use the OAuth solution?
https://developer.smartthings.com/docs/connected-services/oauth-integrations

**Comment by samuelspagl** [comment]
@troyhodges no this is something different. Please refer to the issue mentioned in the README. I will mark your comment as off-topic as is is not targeting the issue listed here :)

**Comment by samuelspagl** [comment]
@wilcocsjr 
> Are there any plans to update this integration to use the OAuth solution? https://developer.smartthings.com/docs/connected-services/oauth-integrations

Theoretically yes. I am first of all waiting for the PR targeting PAT's in the official SmartThings integration.
There is also the possibility to integrate this integration into core. Let's see :)

**Comment by wilcocsjr** [comment]
Are there any news on this?

**Comment by wilcocsjr** [comment]
It seems that the same issue is currently being addressed in home assistant core in this thread: https://github.com/home-assistant/core/issues/133623
Will this fix this integration?

**Comment by wilcocsjr** [comment]
The core integration with SmartThings from today’s update works great with the soundbar and the login is effortless, however it only provides the ability to turn on/off the soundbar and does not allow to change sound modes for example. Will this integration be updated to use this authentication? Would it even be able to access these functionalities?

**Comment by NewsGuyTor** [comment]
You need to go upvote it here:
https://discord.com/channels/1339336957356015626/1339342536040386631

**Comment by nikita-devbox** [comment]
Hi!

HASS core dev worked with Samsung on OAuth, and has created a discord channel to "find out how devices work" (he has 0 Sasmung devices).

I took a stab at it and tried to run a command to play something, but I think due to my lack of I've hit a dead end. I can get the Volume controls to work, but it would be important that one Soundbar owner figures out how to play files and writes "step by step instructions" for other to replicate. Then the ST dev will consider adding it, if it works the same for all soundbar owners.

SmartThings dev channel: https://discord.gg/EJYdwMCz7K
Within there, I got this far: https://discord.com/channels/1339336957356015626/1347838965411221565

**Comment by samuelspagl** [comment]
Hi there ✌️ 

I already replied to @nikita-devbox in another issue.
If I have some free-time the next week(s) I will try to create an MR for core to merge some of the features provided in this custom integration. 

First step from my side is migrating the existing features, therefore I would not focus on playing media files, because I suspect that to be quite tricky.

**Comment by zhdenny** [comment]
Is there any update on this? Repo README here still says to acquire a PAT.......but those are only valid for 24 hours. What do I do?

Using Home Assistant Core official "Smart Things" integration seemed to connect my soundbar nicely. Volume and On/Off function only though.....oh well.

**Comment by kristofferR** [comment]
> Is there any update on this? Repo README here still says to acquire a PAT.......but those are only valid for 24 hours. What do I do?

Use the offical SmartThings HA integration. A LOT of things are still broken though, I'd advice you to avoid Samsung products in the future, I've never been defecated on by a brand like this before.
